### ISSUE TITLE
Bug: joining results in deleted text

### ISSUE THREAD

**Issue by reagle** [Lisiadito/join-lines-plugin#4]
When I past the following into Sublime and go to the first line and hit `alt-j` twice, it joins the first two lines. Hitting `alt-j` a third time deletes the line I'm on and the next line, instead of joining them.

```
 The original Moore’s Law came out of an article I published in 1965 this was the
early days of the integrated circuit, we were just learning to put a few components on a chip. I was
given the chore of predicting what would happen in silicon components in the next 10 years for the
35th anniversary edition of “Electronic Magazine”
```

![micro-join](https://user-images.githubusercontent.com/596814/78181424-5b780300-7432-11ea-85a0-c5c0aff62984.gif)

**Comment by Lisiadito** [comment]
@reagle thanks for reporting the bug. It took me a while to debug. The short version is the character `”` ('RIGHT DOUBLE QUOTATION MARK' (U+201D)) is when I calculate the positions interpreted with a length of three instead of one. It works perfectly when you use `"` ('QUOTATION MARK' (U+0022)). 
I will think about on how I can fix it.

**Comment by Lisiadito** [comment]
fixed the bug in release 1.0.3. I need to open a PR to get it into the plugin channel and will close this issue as soon as that is merged and the new fixed version is officially available.

**Comment by reagle** [comment]
Thank you. Does micro auto-update plugins, or will I have to reinstall manually?

**Comment by Lisiadito** [comment]
You'll need to update manually. Depending on if you use micro 1 or 2 you can either press `ctrl+e` and then type `plugin update PLUGINNAME` or in version two you can do it directly from the command line via `micro -plugin update`

**Comment by reagle** [comment]
I'm running 1.1.0 and still have this bug with the same text.
```
╰─➤  micro -plugin install joinLines
Downloading "joinLines" (1.1.0) from "https://github.com/micro-editor/updated-plugins/releases/download/v1.0.0/join-lines-1.1.0.zip"
One or more plugins installed.
```

**Comment by Lisiadito** [comment]
yes because 1.1.0 ist the old version.
since micro 2 the plugin api changed a bit so for backwards compatibility the offer plugins for micro 1 in this case plugin v1.0.0 und micro 2 plugin v1.1.0
I updated the plugin but they still didn't merge it in their repo. The bug will be fixed in 1.0.3 or 1.1.3 for micro 2. sorry for the wait

**Comment by reagle** [comment]
Is there a specific pull request you can point too?

**Comment by edelvalle** [comment]
I will make one

**Comment by edelvalle** [comment]
here we go #5

**Comment by Lisiadito** [comment]
I opened the PR https://github.com/micro-editor/updated-plugins/pull/7 which gets merged hopefully soon. 
@edelvalle I will still check/test your PR because it seems that your way better in Lua then me and your code looks way more compact and clean. But for me it was important that the Bug is fixed and merged as soon as possible. @reagle sorry for the long wait. The update requires that you update micro to version 2.0.4 since it uses a new util function. 
I will close this issue as soon as the PR is merged.

**Comment by reagle** [comment]
Thanks! I'm running 2.0.4 and looking forward to the bugfix.

**Comment by Lisiadito** [comment]
I got in contact with the repo owner and he pointed out that I need to open a PR against the `plugin-channel` repo and not the `updated-plugin-channel`. It's open now (https://github.com/micro-editor/plugin-channel/pull/54) and I optimistic that it will be merged soon!

**Comment by Lisiadito** [comment]
@reagle PR is merged. You should be able to update the plugin now. If it works you can close this issue.

**Comment by reagle** [comment]
Thank you, but I get an error. 

```
╭─reagle@hom ~
╰─➤  micro -plugin install joinLines
Downloading "joinLines" (1.1.4) from "https://github.com/Lisiadito/join-lines-plugin/archive/v1.1.4.zip"
One or more plugins installed.
╭─reagle@hom ~
╰─➤  micro
joinLines line:20(column:17) near 'selection':   parse error


Press enter to continue
```

**Comment by Lisiadito** [comment]
I'm really sorry about that. Download v1.1.5 and the issue should be resolved

**Comment by reagle** [comment]
Thank you. It will now join lines separated by a single CR/LF. However, it cannot join paragraphs (more than one CR/LF). Is that intentional?

```
This is a line,
with a second line following.

The above can be joined, but this line cannot join that paragraph.
```

**Comment by Lisiadito** [comment]
It can still be joined by selecting all the lines and then pressing the shortcut. 
But you could open a new issue if that is not sufficient enough and I look into it.
